name: Opam build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # Don't trigger if PR only modifies non-code files
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
    - '**.gitignore'
    - '**.opam'
    - '**.nix'
    - 'LICENSE'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**.md'
    - '**.gitignore'
    - '**.opam'
    - '**.nix'
    - 'LICENSE'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Concurrency group used to cancel old runs
concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.head_ref || github.ref }}"
  cancel-in-progress: true
permissions:
  contents: read
env:
  OPAM_PACKAGES: >-
    coq.8.20.1
    coq-equations.1.3.1+8.20
    coq-mathcomp-ssreflect.2.2.0
    coq-mathcomp-analysis.1.2.0
    coq-extructures.0.5.0
    coq-deriving.0.2.0
    coq-mathcomp-word.3.2
  OCAML_COMILER_VERSION: "4.14.2"
  JOBS: 4

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v6

      # Set up OCaml and opam
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ env.OCAML_COMILER_VERSION }}
          opam-repositories: |
            rocq-released: https://rocq-prover.org/opam/released
            default: https://opam.ocaml.org
          opam-pin: false

      - run: sudo apt-get update
      - name: Try to restore opam cache
        id: opam-cache
        uses: actions/cache@v5
        with:
          path: ${{github.workspace}}/_opam
          key: opam-${{github.base_ref}}-${{github.ref}}
          restore-keys: |
            opam--refs/heads/${{github.base_ref}}

      - name: Build dependencies
        run: |
          opam install ${{ env.OPAM_PACKAGES }}
          opam clean -a -c -s --logs

      # Build SSProve
      - name: Build
        run: |
          opam exec -- make -j${{ env.JOBS }}

      # Build coqdoc documentation
      - name: Build documentation
        run: |
          echo "::group::Running coqdoc"
          opam exec -- make -j${{ env.JOBS }} html
          echo "::endgroup::"

          echo "::group::Install dependencies"
          sudo apt install -y graphviz
          echo "::endgroup::"

          echo "::group::Build dependency graphs"
          opam exec -- make -j${{ env.JOBS }} graph
          mv dependencies.svg docs/dependencies.svg
          echo "::endgroup::"

      # Upload documentation
      - name: Prepare documentation for deployment
        # Only upload and deploy documentation when pushing on main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs

  # Deploy coqdoc generated documentation to GitHub pages
  deploy-docs:
    # Only deploy documentation when pushing on main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
